### ISSUE TITLE
ERROR in evaluate and save model. ERROR in training loop or eval/save model.

### ISSUE THREAD

**Issue by JovanBosic** [AarohiSingla/YOLOv6-on-Custom-Dataset#1]
Training start...

 Epoch  iou_loss   l1_loss  obj_loss  cls_loss
0%| | 0/691 [00:00<?, ?it/s] /home/acus/anaconda3/envs/mengshan/lib/python3.8/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:2228.)
return _VF.meshgrid(tensors, **kwargs) # type: ignore[attr-defined]
0/399 2.178 1.209 3.51 1.606: 100%|██████████| 691/691 [02:23<00:00,
Inferencing model in val datasets.: 100%|███████████████████| 87/87 [00:37<00:00, 2.32it/s]

Evaluating speed.

Evaluating mAP by pycocotools.
Saving runs/train/exp6/predictions.json...
loading annotations into memory...
Done (t=0.04s)
creating index...
index created!
Loading and preparing results...
DONE (t=4.52s)
creating index...
index created!
ERROR in evaluate and save model.
ERROR in training loop or eval/save model.

Training completed in 0.053 hours.
Traceback (most recent call last):
File "tools/train.py", line 112, in
main(args)
File "tools/train.py", line 102, in main
trainer.train()
File "/media/acus/new_disk/meng/YOLOv6-main/yolov6/core/engine.py", line 75, in train
self.train_in_loop()
File "/media/acus/new_disk/meng/YOLOv6-main/yolov6/core/engine.py", line 94, in train_in_loop
self.eval_and_save()
File "/media/acus/new_disk/meng/YOLOv6-main/yolov6/core/engine.py", line 120, in eval_and_save
self.eval_model()
File "/media/acus/new_disk/meng/YOLOv6-main/yolov6/core/engine.py", line 139, in eval_model
results = eval.run(self.data_dict,
File "/home/acus/anaconda3/envs/mengshan/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "/media/acus/new_disk/meng/YOLOv6-main/tools/eval.py", line 83, in run
eval_result = val.eval_model(pred_result, model, dataloader, task)
File "/media/acus/new_disk/meng/YOLOv6-main/yolov6/core/evaler.py", line 128, in eval_model
cocoEval = COCOeval(anno, pred, 'bbox')
File "/home/acus/anaconda3/envs/mengshan/lib/python3.8/site-packages/pycocotools/cocoeval.py", line 80, in init
self.params.imgIds = sorted(cocoGt.getImgIds())
TypeError: '<' not supported between instances of 'str' and 'int'

After the training is completed, before the evaluation results, I am getting the following error. I would really appreciate it, to get some insights on how to go about this issue as soon as possible.

I have tried to train YOLOv6 on smaller dataset containing images with similar names, and it worked perfectly. In whole dataset I have .jpg and .png files, I also tried to exclude .png files and it didt help. Is there any chance you can help me? I also tried to train model on coco annotation and yolo annotation and the error is the same. Huge thank you in advance.

**Comment by JovanBosic** [comment]
I have solved this. If the name of the image consists only of numbers like for example '12345311232.jpg' this problem occurs and the images must be removed from the dataset so that the algorithm can be trained and evaluated.
